spring.application.name=GymPlanner

# ===============================
# CONFIGURARE SQL SERVER (SSMS)
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GymPlannerBD;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# CONFIGURARE JPA / HIBERNATE
# ===============================
# Asta ii spune lui Java ce "dialect" de SQL folosim
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Arata query-urile SQL in consola (util pentru debug)
spring.jpa.show-sql=true

# Actualizeaza baza de date automat (dar noi avem deja scriptul SQL, deci punem 'validate' sau 'none' sau 'update')
# 'update' e bun la inceput: daca adaugi o coloana in Java, o pune si in SQL.
spring.jpa.hibernate.ddl-auto=update
# Aceasta linie obliga Java sa nu transforme "ExerciseName" in "exercise_name"
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl